/* Database schema to keep the structure of entire database. */

 CREATE TABLE animals (
 ID            INT    PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 NAME   CHAR(50)                  NOT NULL,
 DATE_OF_BIRTH     DATE           NOT NULL,
 ESCAPE_ATTEMPTS   INT            NOT NULL,
 NEUTERED          BOOLEAN        NOT NULL,
 WEIGHT_KG         DECIMAL,
SPECIES            VARCHAR
 );
 
//Create table owners 
CREATE TABLE owners (
 ID      INT  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 FULL_NAME    CHAR(20)  NOT NULL,
 AGE       INT  NOT NULL,
 PRIMARY KEY(ID)
 );

//Create table species
CREATE TABLE species ( 
 ID     INT    NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
 NAME     VARCHAR(20),
 PRIMARY KEY(ID)
);


//Create and Make species_id column refrence species table
ALTER TABLE animals
ADD COLUMN species_id INT;

ALTER TABLE animals
ADD FOREIGN KEY (species_id) REFERENCES species(ID);


//Create and Make owners_id column  refrence owners table
ALTER TABLE animals
ADD COLUMN owner_id 

ALTER TABLE animals
ADD FOREIGN KEY (owner_id) REFERENCES owners(ID);

CREATE TABLE vets (
 ID     INT    NOT NULL  GENERATED BY DEFAULT AS IDENTITY,
 NAME   VARCHAR(20),
 AGE    INT,
 DATE_OF_GRADUATION DATE,
 PRIMARY KEY(ID)
);



CREATE TABLE specialty (
 VET_ID CHAR,
 SPECIALTY_ID CHAR
);


CREATE TABLE visits (
ANIMAL_ID INT,
VET_ID INT,
DATE_OF_VISIT DATE
);


CREATE INDEX animal_index ON visits(animal_id ASC);
